### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by ghost** [ryanneph/Raytrace#1]
Hey Ryan,

I am having a difficult time compiling your code on windows. I would list some errors, but I have tried too many things and have lost track. Have you been able to do so? What is your environment, version of python, compiler, version of CUDA, etc...

Thanks!

**Comment by ryanneph** [comment]
I can't really support windows installation of cuda components, but I have implemented CPU fallbacks to all of the functions. Try installing from the https://github.com/ryanneph/Raytrace/tree/cpu_fallback branch and let me know if it helps.
